#!/bin/bash
set -e

# =============================================================================
# Generate .env file from Terraform outputs
# =============================================================================
# This script generates a .env file for the UI service using values from
# Terraform outputs and the .env.example template
#
# Usage:
#   ./env.sh [environment]
#
# Arguments:
#   environment - Environment name (default: dev)
# =============================================================================

ENVIRONMENT="${1:-dev}"

echo "🔧 Generating .env file for environment: $ENVIRONMENT"

# Get Terraform outputs
cd ../../infra/core

echo "📋 Reading Terraform outputs..."

# Check if Terraform is initialized
if [ ! -d ".terraform" ]; then
    echo "❌ Terraform is not initialized in infra/core"
    echo "   Please run: cd infra/core && terraform init -backend-config=backends/backend-$ENVIRONMENT.hcl"
    exit 1
fi

# Get required outputs
AZURE_CLIENT_ID=$(terraform output -raw azure_ad_application_id 2>/dev/null || echo "")
AZURE_TENANT_ID=$(terraform output -raw azure_ad_tenant_id 2>/dev/null || echo "")

cd ../../services/ui

# Validate outputs
if [ -z "$AZURE_CLIENT_ID" ]; then
    echo "❌ Error: azure_ad_application_id not found in Terraform outputs"
    echo "   Make sure Terraform has been applied and outputs are available"
    exit 1
fi

if [ -z "$AZURE_TENANT_ID" ]; then
    echo "❌ Error: azure_ad_tenant_id not found in Terraform outputs"
    echo "   Make sure Terraform has been applied and outputs are available"
    exit 1
fi

# Generate .env file
echo "📝 Generating .env file..."

cat > .env << EOF
# Environment Configuration - Generated by env.sh
# Environment: $ENVIRONMENT
# Generated: $(date)

# API URL for backend API
VITE_API_URL=/api

# WebSocket URL for real-time chat
VITE_WS_URL=/api/ws

# AI Chat API URL
VITE_AI_CHAT_URL=/ai-chat

# WebRTC Signaling URL
VITE_WEBRTC_SIGNALING_URL=/wrtc-api

# Azure AD Authentication
VITE_AUTH_CLIENT_ID=$AZURE_CLIENT_ID
VITE_AUTH_TENANT_ID=$AZURE_TENANT_ID
EOF

echo "✅ .env file generated successfully!"
echo ""
echo "📄 Generated values:"
echo "   VITE_API_URL=/api"
echo "   VITE_WS_URL=/api/ws"
echo "   VITE_AI_CHAT_URL=/ai-chat"
echo "   VITE_WEBRTC_SIGNALING_URL=/wrtc-api"
echo "   VITE_AUTH_CLIENT_ID=$AZURE_CLIENT_ID"
echo "   VITE_AUTH_TENANT_ID=$AZURE_TENANT_ID"
echo ""
