#!/bin/bash
set -e

# =============================================================================
# Generate .env file from Terraform outputs
# =============================================================================
# This script generates a .env file for the AI Chat service using values from
# Terraform outputs
#
# Usage:
#   ./env.sh [environment]
#
# Arguments:
#   environment - Environment name (default: dev)
# =============================================================================

ENVIRONMENT="${1:-dev}"

echo "🔧 Generating .env file for environment: $ENVIRONMENT"

# Get Terraform outputs
cd ../../infra/core

echo "📋 Reading Terraform outputs..."

# Check if Terraform is initialized
if [ ! -d ".terraform" ]; then
    echo "❌ Terraform is not initialized in infra/core"
    echo "   Please run: cd infra/core && terraform init -backend-config=backends/backend-$ENVIRONMENT.hcl"
    exit 1
fi

# Get required outputs
AZURE_CLIENT_ID=$(terraform output -raw azure_ad_application_id 2>/dev/null || echo "")
AZURE_TENANT_ID=$(terraform output -raw azure_ad_tenant_id 2>/dev/null || echo "")

cd ../../services/ai-chat

# Validate outputs
if [ -z "$AZURE_CLIENT_ID" ]; then
    echo "❌ Error: azure_ad_application_id not found in Terraform outputs"
    echo "   Make sure Terraform has been applied and outputs are available"
    exit 1
fi

if [ -z "$AZURE_TENANT_ID" ]; then
    echo "❌ Error: azure_ad_tenant_id not found in Terraform outputs"
    echo "   Make sure Terraform has been applied and outputs are available"
    exit 1
fi

# Generate .env file
echo "📝 Generating .env file..."

cat > .env << EOF
# Environment Configuration - Generated by env.sh
# Environment: $ENVIRONMENT
# Generated: $(date)

# Application Settings
APP_NAME=AI Chat Service
ENVIRONMENT=$ENVIRONMENT
DEBUG=false
LOG_LEVEL=info

# API Settings
API_VERSION=v1

# Azure AD JWT Authentication
AZURE_AD_TENANT_ID=$AZURE_TENANT_ID
AZURE_AD_CLIENT_ID=$AZURE_CLIENT_ID

# Development Only - DO NOT SET TO true IN PRODUCTION
SKIP_TOKEN_VERIFICATION=false
EOF

echo "✅ .env file generated successfully!"
echo ""
echo "📄 Generated values:"
echo "   APP_NAME=AI Chat Service"
echo "   ENVIRONMENT=$ENVIRONMENT"
echo "   DEBUG=false"
echo "   LOG_LEVEL=info"
echo "   API_VERSION=v1"
echo "   AZURE_AD_TENANT_ID=$AZURE_TENANT_ID"
echo "   AZURE_AD_CLIENT_ID=$AZURE_CLIENT_ID"
echo "   SKIP_TOKEN_VERIFICATION=false"
echo ""
