#!/bin/bash
set -e

# =============================================================================
# Generate .env file from Terraform outputs
# =============================================================================
# This script generates a .env file for the API service using values from
# Terraform outputs
#
# Usage:
#   ./env.sh [environment]
#
# Arguments:
#   environment - Environment name (default: dev)
# =============================================================================

ENVIRONMENT="${1:-dev}"

echo "🔧 Generating .env file for environment: $ENVIRONMENT"

# Get Terraform outputs
cd ../../infra/core

echo "📋 Reading Terraform outputs..."

# Check if Terraform is initialized
if [ ! -d ".terraform" ]; then
    echo "❌ Terraform is not initialized in infra/core"
    echo "   Please run: cd infra/core && terraform init -backend-config=backends/backend-$ENVIRONMENT.hcl"
    exit 1
fi

# Get required outputs
AZURE_CLIENT_ID=$(terraform output -raw azure_ad_client_id 2>/dev/null || echo "")
AZURE_TENANT_ID=$(terraform output -raw azure_ad_tenant_id 2>/dev/null || echo "")

cd ../../services/api

# Validate outputs
if [ -z "$AZURE_CLIENT_ID" ]; then
    echo "⚠️  Warning: azure_ad_client_id not found in Terraform outputs"
    AZURE_CLIENT_ID="your-client-id-here"
fi

if [ -z "$AZURE_TENANT_ID" ]; then
    echo "⚠️  Warning: azure_ad_tenant_id not found in Terraform outputs"
    AZURE_TENANT_ID="your-tenant-id-here"
fi

# Generate .env file
echo "📝 Generating .env file..."

cat > .env << EOF
# Environment Configuration - Generated by env.sh
# Environment: $ENVIRONMENT
# Generated: $(date)

# Server Configuration
PORT=8080

# Azure AD Authentication
AZURE_TENANT_ID=$AZURE_TENANT_ID
AZURE_CLIENT_ID=$AZURE_CLIENT_ID

# Development Only - DO NOT SET TO true IN PRODUCTION
SKIP_TOKEN_VERIFICATION=false
EOF

echo "✅ .env file generated successfully!"
echo ""
echo "📄 Generated values:"
echo "   PORT=8080"
echo "   AZURE_TENANT_ID=$AZURE_TENANT_ID"
echo "   AZURE_CLIENT_ID=$AZURE_CLIENT_ID"
echo "   SKIP_TOKEN_VERIFICATION=false"
echo ""
